#!/bin/bash

##############################################################################
# CSS Optimizer Script
# 自动提取项目中使用的 Remixicon 图标和 Animate.css 动画
# 生成精简版 CSS 文件
##############################################################################

set -e  # 遇到错误立即退出

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# 项目路径
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LAYOUTS_DIR="${PROJECT_ROOT}/themes/zozo/layouts"
CUSTOM_LAYOUTS_DIR="${PROJECT_ROOT}/layouts"
STATIC_CSS_DIR="${PROJECT_ROOT}/themes/zozo/static/css"
REMIXICON_SOURCE="${STATIC_CSS_DIR}/remixicon.css"
ANIMATE_SOURCE="${STATIC_CSS_DIR}/animate.min.css"
REMIXICON_OUTPUT="${STATIC_CSS_DIR}/remixicon-custom.css"
ANIMATE_OUTPUT="${STATIC_CSS_DIR}/animate-custom.css"

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}  CSS 优化脚本${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

##############################################################################
# 1. 提取 Remixicon 图标
##############################################################################

echo -e "${YELLOW}[1/4] 扫描项目中使用的 Remixicon 图标...${NC}"

# 优先从 hugo_stats.json 提取图标类名（如果存在）
HUGO_STATS_FILE="${PROJECT_ROOT}/hugo_stats.json"
if [ -f "$HUGO_STATS_FILE" ]; then
    echo -e "${BLUE}  → 从 hugo_stats.json 提取图标类名${NC}"
    REMIXICON_CLASSES=$(grep -o '"ri-[a-z0-9-]*"' "$HUGO_STATS_FILE" | \
        tr -d '"' | \
        sort -u | \
        grep -v '^ri-$' || true)
else
    # 回退方案：从 HTML 模板中提取
    echo -e "${BLUE}  → 从 HTML 模板提取图标类名${NC}"
    REMIXICON_CLASSES=$(find "${LAYOUTS_DIR}" "${CUSTOM_LAYOUTS_DIR}" -type f -name "*.html" 2>/dev/null | \
        xargs grep -oh 'class="[^"]*ri-[^"]*"' 2>/dev/null | \
        grep -o 'ri-[a-z0-9-]*' | \
        sort -u | \
        grep -v '^ri-$' || true)
fi

if [ -z "$REMIXICON_CLASSES" ]; then
    echo -e "${RED}  ✗ 未找到任何 Remixicon 图标${NC}"
    exit 1
fi

# 统计数量
ICON_COUNT=$(echo "$REMIXICON_CLASSES" | wc -l | tr -d ' ')
echo -e "${GREEN}  ✓ 找到 ${ICON_COUNT} 个图标:${NC}"
echo "$REMIXICON_CLASSES" | sed 's/^/    - /'
echo ""

##############################################################################
# 2. 生成 remixicon-custom.css
##############################################################################

echo -e "${YELLOW}[2/4] 生成 remixicon-custom.css...${NC}"

# 检查源文件
if [ ! -f "$REMIXICON_SOURCE" ]; then
    echo -e "${RED}  ✗ 源文件不存在: $REMIXICON_SOURCE${NC}"
    exit 1
fi

# 提取原始文件大小
ORIGINAL_SIZE=$(du -h "$REMIXICON_SOURCE" | cut -f1)

# 生成文件头
cat > "$REMIXICON_OUTPUT" << 'EOF'
/*
* Remix Icon - Custom Build
* Auto-generated by optimize-css.sh
* Only includes icons actually used in the theme
*/
EOF

# 提取 @font-face 声明
echo "" >> "$REMIXICON_OUTPUT"
sed -n '/^@font-face/,/^}/p' "$REMIXICON_SOURCE" >> "$REMIXICON_OUTPUT"

# 提取基础样式
echo "" >> "$REMIXICON_OUTPUT"
sed -n '/^\[class\^="ri-"\]/,/^}/p' "$REMIXICON_SOURCE" >> "$REMIXICON_OUTPUT"

# 添加注释
echo "" >> "$REMIXICON_OUTPUT"
echo "/* Only include the ${ICON_COUNT} icons actually used */" >> "$REMIXICON_OUTPUT"

# 提取每个图标的 CSS 规则
for icon in $REMIXICON_CLASSES; do
    grep "^\\.${icon}:before" "$REMIXICON_SOURCE" >> "$REMIXICON_OUTPUT" 2>/dev/null || {
        echo -e "${RED}  ✗ 警告: 未找到图标 ${icon} 的定义${NC}"
    }
done

# 计算优化后的大小
OPTIMIZED_SIZE=$(du -h "$REMIXICON_OUTPUT" | cut -f1)
echo -e "${GREEN}  ✓ 生成成功: ${REMIXICON_OUTPUT}${NC}"
echo -e "    原始大小: ${ORIGINAL_SIZE} → 优化后: ${OPTIMIZED_SIZE}"
echo ""

##############################################################################
# 3. 提取 Animate.css 动画
##############################################################################

echo -e "${YELLOW}[3/4] 扫描项目中使用的 Animate.css 动画...${NC}"

# 优先从 hugo_stats.json 提取动画类名（如果存在）
if [ -f "$HUGO_STATS_FILE" ]; then
    echo -e "${BLUE}  → 从 hugo_stats.json 提取动画类名${NC}"
    ANIMATION_NAMES=$(grep -o '"animate__[a-zA-Z]*"' "$HUGO_STATS_FILE" | \
        tr -d '"' | \
        grep -v '^animate__animated$' | \
        sed 's/animate__//' | \
        sort -u || true)
else
    # 回退方案：从 HTML 模板中提取
    echo -e "${BLUE}  → 从 HTML 模板提取动画类名${NC}"
    ANIMATION_NAMES=$(find "${LAYOUTS_DIR}" "${CUSTOM_LAYOUTS_DIR}" -type f -name "*.html" 2>/dev/null | \
        xargs grep -oh 'animate__[a-zA-Z]*' 2>/dev/null | \
        grep -v '^animate__animated$' | \
        sed 's/animate__//' | \
        sort -u || true)
fi

if [ -z "$ANIMATION_NAMES" ]; then
    echo -e "${RED}  ✗ 未找到任何 Animate.css 动画${NC}"
    exit 1
fi

# 统计数量
ANIM_COUNT=$(echo "$ANIMATION_NAMES" | wc -l | tr -d ' ')
echo -e "${GREEN}  ✓ 找到 ${ANIM_COUNT} 个动画:${NC}"
echo "$ANIMATION_NAMES" | sed 's/^/    - animate__/'
echo ""

##############################################################################
# 4. 生成 animate-custom.css（手动处理压缩CSS）
##############################################################################

echo -e "${YELLOW}[4/4] 生成 animate-custom.css...${NC}"

# 检查源文件
if [ ! -f "$ANIMATE_SOURCE" ]; then
    echo -e "${RED}  ✗ 源文件不存在: $ANIMATE_SOURCE${NC}"
    exit 1
fi

# 提取原始文件大小
ANIMATE_ORIGINAL_SIZE=$(du -h "$ANIMATE_SOURCE" | cut -f1)

# 手动生成精简版 animate.css
cat > "$ANIMATE_OUTPUT" << 'EOF'
/*
* Animate.css - Custom Build
* Auto-generated by optimize-css.sh
* Only includes animations actually used
*/
.animate__animated {
  -webkit-animation-duration: 1s;
  animation-duration: 1s;
  -webkit-animation-fill-mode: both;
  animation-fill-mode: both;
}

EOF

# 为每个动画生成 CSS（手动编写常用动画）
for anim in $ANIMATION_NAMES; do
    case $anim in
        fadeInDown)
            cat >> "$ANIMATE_OUTPUT" << 'EOF'
@-webkit-keyframes fadeInDown {
  from {
    opacity: 0;
    -webkit-transform: translate3d(0, -100%, 0);
    transform: translate3d(0, -100%, 0);
  }
  to {
    opacity: 1;
    -webkit-transform: translate3d(0, 0, 0);
    transform: translate3d(0, 0, 0);
  }
}

@keyframes fadeInDown {
  from {
    opacity: 0;
    -webkit-transform: translate3d(0, -100%, 0);
    transform: translate3d(0, -100%, 0);
  }
  to {
    opacity: 1;
    -webkit-transform: translate3d(0, 0, 0);
    transform: translate3d(0, 0, 0);
  }
}

.animate__fadeInDown {
  -webkit-animation-name: fadeInDown;
  animation-name: fadeInDown;
}

EOF
            ;;
        fadeIn)
            cat >> "$ANIMATE_OUTPUT" << 'EOF'
@-webkit-keyframes fadeIn {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}

@keyframes fadeIn {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}

.animate__fadeIn {
  -webkit-animation-name: fadeIn;
  animation-name: fadeIn;
}

EOF
            ;;
        *)
            echo -e "${YELLOW}  ! 警告: 未实现动画 ${anim}, 请手动添加${NC}"
            ;;
    esac
done

# 计算优化后的大小
ANIMATE_OPTIMIZED_SIZE=$(du -h "$ANIMATE_OUTPUT" | cut -f1)
echo -e "${GREEN}  ✓ 生成成功: ${ANIMATE_OUTPUT}${NC}"
echo -e "    原始大小: ${ANIMATE_ORIGINAL_SIZE} → 优化后: ${ANIMATE_OPTIMIZED_SIZE}"
echo ""

##############################################################################
# 总结
##############################################################################

echo -e "${BLUE}========================================${NC}"
echo -e "${GREEN}✓ CSS 优化完成!${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo -e "统计信息:"
echo -e "  • Remixicon 图标: ${ICON_COUNT} 个"
echo -e "  • Animate.css 动画: ${ANIM_COUNT} 个"
echo ""
echo -e "文件大小:"
echo -e "  • remixicon.css:        ${ORIGINAL_SIZE} → ${OPTIMIZED_SIZE}"
echo -e "  • animate.min.css:      ${ANIMATE_ORIGINAL_SIZE} → ${ANIMATE_OPTIMIZED_SIZE}"
echo ""
echo -e "${YELLOW}提示:${NC}"
echo -e "  1. 请运行 'hugo server' 预览效果"
echo -e "  2. 确认无误后运行 'hugo' 重新构建站点"
echo -e "  3. 提交更改: git add . && git commit -m 'chore: 优化 CSS 资源'"
echo ""
